/**
 * Birth-place dataset. In production this would be a geocoding service;
 * here it's a static, searchable list so the user never types coordinates.
 */

export interface Place {
  name: string;
  country: string;
  admin?: string;
  latitude: number;
  longitude: number;
  timezone: string;
}

const IN = "Asia/Kolkata";

export const PLACES: Place[] = [
  { name: "Mumbai", country: "India", admin: "Maharashtra", latitude: 19.076, longitude: 72.8777, timezone: IN },
  { name: "Delhi", country: "India", admin: "Delhi", latitude: 28.6139, longitude: 77.209, timezone: IN },
  { name: "New Delhi", country: "India", admin: "Delhi", latitude: 28.6139, longitude: 77.209, timezone: IN },
  { name: "Bengaluru", country: "India", admin: "Karnataka", latitude: 12.9716, longitude: 77.5946, timezone: IN },
  { name: "Bangalore", country: "India", admin: "Karnataka", latitude: 12.9716, longitude: 77.5946, timezone: IN },
  { name: "Hyderabad", country: "India", admin: "Telangana", latitude: 17.385, longitude: 78.4867, timezone: IN },
  { name: "Chennai", country: "India", admin: "Tamil Nadu", latitude: 13.0827, longitude: 80.2707, timezone: IN },
  { name: "Madras", country: "India", admin: "Tamil Nadu", latitude: 13.0827, longitude: 80.2707, timezone: IN },
  { name: "Kolkata", country: "India", admin: "West Bengal", latitude: 22.5726, longitude: 88.3639, timezone: IN },
  { name: "Calcutta", country: "India", admin: "West Bengal", latitude: 22.5726, longitude: 88.3639, timezone: IN },
  { name: "Pune", country: "India", admin: "Maharashtra", latitude: 18.5204, longitude: 73.8567, timezone: IN },
  { name: "Ahmedabad", country: "India", admin: "Gujarat", latitude: 23.0225, longitude: 72.5714, timezone: IN },
  { name: "Surat", country: "India", admin: "Gujarat", latitude: 21.1702, longitude: 72.8311, timezone: IN },
  { name: "Jaipur", country: "India", admin: "Rajasthan", latitude: 26.9124, longitude: 75.7873, timezone: IN },
  { name: "Lucknow", country: "India", admin: "Uttar Pradesh", latitude: 26.8467, longitude: 80.9462, timezone: IN },
  { name: "Kanpur", country: "India", admin: "Uttar Pradesh", latitude: 26.4499, longitude: 80.3319, timezone: IN },
  { name: "Nagpur", country: "India", admin: "Maharashtra", latitude: 21.1458, longitude: 79.0882, timezone: IN },
  { name: "Indore", country: "India", admin: "Madhya Pradesh", latitude: 22.7196, longitude: 75.8577, timezone: IN },
  { name: "Bhopal", country: "India", admin: "Madhya Pradesh", latitude: 23.2599, longitude: 77.4126, timezone: IN },
  { name: "Patna", country: "India", admin: "Bihar", latitude: 25.5941, longitude: 85.1376, timezone: IN },
  { name: "Ranchi", country: "India", admin: "Jharkhand", latitude: 23.3441, longitude: 77.1097, timezone: IN },
  { name: "Guwahati", country: "India", admin: "Assam", latitude: 26.1445, longitude: 91.7362, timezone: IN },
  { name: "Chandigarh", country: "India", admin: "Chandigarh", latitude: 30.7333, longitude: 76.7794, timezone: IN },
  { name: "Dehradun", country: "India", admin: "Uttarakhand", latitude: 30.3165, longitude: 78.0322, timezone: IN },
  { name: "Shimla", country: "India", admin: "Himachal Pradesh", latitude: 31.1048, longitude: 77.1734, timezone: IN },
  { name: "Amritsar", country: "India", admin: "Punjab", latitude: 31.634, longitude: 74.8723, timezone: IN },
  { name: "Ludhiana", country: "India", admin: "Punjab", latitude: 30.901, longitude: 75.8573, timezone: IN },
  { name: "Jalandhar", country: "India", admin: "Punjab", latitude: 31.326, longitude: 75.5762, timezone: IN },
  { name: "Varanasi", country: "India", admin: "Uttar Pradesh", latitude: 25.3176, longitude: 82.9739, timezone: IN },
  { name: "Benares", country: "India", admin: "Uttar Pradesh", latitude: 25.3176, longitude: 82.9739, timezone: IN },
  { name: "Prayagraj", country: "India", admin: "Uttar Pradesh", latitude: 25.4358, longitude: 81.8463, timezone: IN },
  { name: "Allahabad", country: "India", admin: "Uttar Pradesh", latitude: 25.4358, longitude: 81.8463, timezone: IN },
  { name: "Agra", country: "India", admin: "Uttar Pradesh", latitude: 27.1767, longitude: 78.0081, timezone: IN },
  { name: "Mathura", country: "India", admin: "Uttar Pradesh", latitude: 27.4924, longitude: 77.6737, timezone: IN },
  { name: "Vrindavan", country: "India", admin: "Uttar Pradesh", latitude: 27.58, longitude: 77.7, timezone: IN },
  { name: "Ayodhya", country: "India", admin: "Uttar Pradesh", latitude: 26.7996, longitude: 82.2041, timezone: IN },
  { name: "Haridwar", country: "India", admin: "Uttarakhand", latitude: 29.9457, longitude: 78.1642, timezone: IN },
  { name: "Rishikesh", country: "India", admin: "Uttarakhand", latitude: 30.0869, longitude: 78.2676, timezone: IN },
  { name: "Noida", country: "India", admin: "Uttar Pradesh", latitude: 28.5355, longitude: 77.391, timezone: IN },
  { name: "Gurugram", country: "India", admin: "Haryana", latitude: 28.4595, longitude: 77.0266, timezone: IN },
  { name: "Gurgaon", country: "India", admin: "Haryana", latitude: 28.4595, longitude: 77.0266, timezone: IN },
  { name: "Faridabad", country: "India", admin: "Haryana", latitude: 28.4089, longitude: 77.3178, timezone: IN },
  { name: "Ghaziabad", country: "India", admin: "Uttar Pradesh", latitude: 28.6692, longitude: 77.4538, timezone: IN },
  { name: "Meerut", country: "India", admin: "Uttar Pradesh", latitude: 28.9845, longitude: 77.7064, timezone: IN },
  { name: "Bareilly", country: "India", admin: "Uttar Pradesh", latitude: 28.367, longitude: 79.4304, timezone: IN },
  { name: "Aligarh", country: "India", admin: "Uttar Pradesh", latitude: 27.8974, longitude: 78.0886, timezone: IN },
  { name: "Gorakhpur", country: "India", admin: "Uttar Pradesh", latitude: 26.7606, longitude: 83.3732, timezone: IN },
  { name: "Jodhpur", country: "India", admin: "Rajasthan", latitude: 26.2389, longitude: 73.0243, timezone: IN },
  { name: "Udaipur", country: "India", admin: "Rajasthan", latitude: 24.5854, longitude: 73.7125, timezone: IN },
  { name: "Kota", country: "India", admin: "Rajasthan", latitude: 25.2138, longitude: 75.8648, timezone: IN },
  { name: "Bikaner", country: "India", admin: "Rajasthan", latitude: 28.0229, longitude: 73.3119, timezone: IN },
  { name: "Ajmer", country: "India", admin: "Rajasthan", latitude: 26.4499, longitude: 74.6399, timezone: IN },
  { name: "Pushkar", country: "India", admin: "Rajasthan", latitude: 26.4874, longitude: 74.5511, timezone: IN },
  { name: "Thiruvananthapuram", country: "India", admin: "Kerala", latitude: 8.5241, longitude: 76.9366, timezone: IN },
  { name: "Trivandrum", country: "India", admin: "Kerala", latitude: 8.5241, longitude: 76.9366, timezone: IN },
  { name: "Kochi", country: "India", admin: "Kerala", latitude: 9.9312, longitude: 76.2673, timezone: IN },
  { name: "Cochin", country: "India", admin: "Kerala", latitude: 9.9312, longitude: 76.2673, timezone: IN },
  { name: "Kozhikode", country: "India", admin: "Kerala", latitude: 11.2588, longitude: 75.7804, timezone: IN },
  { name: "Calicut", country: "India", admin: "Kerala", latitude: 11.2588, longitude: 75.7804, timezone: IN },
  { name: "Thrissur", country: "India", admin: "Kerala", latitude: 10.5276, longitude: 76.2144, timezone: IN },
  { name: "Kollam", country: "India", admin: "Kerala", latitude: 8.8932, longitude: 76.6141, timezone: IN },
  { name: "Kannur", country: "India", admin: "Kerala", latitude: 11.8745, longitude: 75.3704, timezone: IN },
  { name: "Palakkad", country: "India", admin: "Kerala", latitude: 10.7867, longitude: 76.6548, timezone: IN },
  { name: "Coimbatore", country: "India", admin: "Tamil Nadu", latitude: 11.0168, longitude: 76.9558, timezone: IN },
  { name: "Madurai", country: "India", admin: "Tamil Nadu", latitude: 9.9252, longitude: 78.1198, timezone: IN },
  { name: "Tiruchirappalli", country: "India", admin: "Tamil Nadu", latitude: 10.7905, longitude: 78.7047, timezone: IN },
  { name: "Trichy", country: "India", admin: "Tamil Nadu", latitude: 10.7905, longitude: 78.7047, timezone: IN },
  { name: "Salem", country: "India", admin: "Tamil Nadu", latitude: 11.6643, longitude: 78.146, timezone: IN },
  { name: "Tirunelveli", country: "India", admin: "Tamil Nadu", latitude: 8.7139, longitude: 77.7567, timezone: IN },
  { name: "Erode", country: "India", admin: "Tamil Nadu", latitude: 11.341, longitude: 77.7172, timezone: IN },
  { name: "Vellore", country: "India", admin: "Tamil Nadu", latitude: 12.9165, longitude: 79.1325, timezone: IN },
  { name: "Thanjavur", country: "India", admin: "Tamil Nadu", latitude: 10.787, longitude: 79.1378, timezone: IN },
  { name: "Puducherry", country: "India", admin: "Puducherry", latitude: 11.9416, longitude: 79.8083, timezone: IN },
  { name: "Pondicherry", country: "India", admin: "Puducherry", latitude: 11.9416, longitude: 79.8083, timezone: IN },
  { name: "Visakhapatnam", country: "India", admin: "Andhra Pradesh", latitude: 17.6868, longitude: 83.2185, timezone: IN },
  { name: "Vizag", country: "India", admin: "Andhra Pradesh", latitude: 17.6868, longitude: 83.2185, timezone: IN },
  { name: "Vijayawada", country: "India", admin: "Andhra Pradesh", latitude: 16.5062, longitude: 80.648, timezone: IN },
  { name: "Guntur", country: "India", admin: "Andhra Pradesh", latitude: 16.3067, longitude: 80.4365, timezone: IN },
  { name: "Tirupati", country: "India", admin: "Andhra Pradesh", latitude: 13.6288, longitude: 79.4192, timezone: IN },
  { name: "Warangal", country: "India", admin: "Telangana", latitude: 17.9689, longitude: 79.5941, timezone: IN },
  { name: "Nizamabad", country: "India", admin: "Telangana", latitude: 18.6725, longitude: 78.0941, timezone: IN },
  { name: "Mysuru", country: "India", admin: "Karnataka", latitude: 12.2958, longitude: 76.6394, timezone: IN },
  { name: "Mysore", country: "India", admin: "Karnataka", latitude: 12.2958, longitude: 76.6394, timezone: IN },
  { name: "Mangaluru", country: "India", admin: "Karnataka", latitude: 12.9148, longitude: 74.856, timezone: IN },
  { name: "Mangalore", country: "India", admin: "Karnataka", latitude: 12.9148, longitude: 74.856, timezone: IN },
  { name: "Hubballi", country: "India", admin: "Karnataka", latitude: 15.3647, longitude: 75.124, timezone: IN },
  { name: "Hubli", country: "India", admin: "Karnataka", latitude: 15.3647, longitude: 75.124, timezone: IN },
  { name: "Belagavi", country: "India", admin: "Karnataka", latitude: 15.8497, longitude: 74.4977, timezone: IN },
  { name: "Belgaum", country: "India", admin: "Karnataka", latitude: 15.8497, longitude: 74.4977, timezone: IN },
  { name: "Davanagere", country: "India", admin: "Karnataka", latitude: 14.4673, longitude: 75.9217, timezone: IN },
  { name: "Udupi", country: "India", admin: "Karnataka", latitude: 13.3409, longitude: 74.7421, timezone: IN },
  { name: "Vadodara", country: "India", admin: "Gujarat", latitude: 22.3072, longitude: 73.1812, timezone: IN },
  { name: "Baroda", country: "India", admin: "Gujarat", latitude: 22.3072, longitude: 73.1812, timezone: IN },
  { name: "Rajkot", country: "India", admin: "Gujarat", latitude: 22.3039, longitude: 70.8022, timezone: IN },
  { name: "Bhavnagar", country: "India", admin: "Gujarat", latitude: 21.7645, longitude: 72.1516, timezone: IN },
  { name: "Jamnagar", country: "India", admin: "Gujarat", latitude: 22.4722, longitude: 70.0578, timezone: IN },
  { name: "Gandhinagar", country: "India", admin: "Gujarat", latitude: 23.2156, longitude: 72.6369, timezone: IN },
  { name: "Anand", country: "India", admin: "Gujarat", latitude: 22.5645, longitude: 72.9289, timezone: IN },
  { name: "Junagadh", country: "India", admin: "Gujarat", latitude: 21.5222, longitude: 70.4579, timezone: IN },
  { name: "Kutch", country: "India", admin: "Gujarat", latitude: 23.2419, longitude: 69.6669, timezone: IN },
  { name: "Nashik", country: "India", admin: "Maharashtra", latitude: 19.9975, longitude: 73.7898, timezone: IN },
  { name: "Aurangabad", country: "India", admin: "Maharashtra", latitude: 19.8762, longitude: 75.3433, timezone: IN },
  { name: "Solapur", country: "India", admin: "Maharashtra", latitude: 17.6599, longitude: 75.9064, timezone: IN },
  { name: "Kolhapur", country: "India", admin: "Maharashtra", latitude: 16.705, longitude: 74.2433, timezone: IN },
  { name: "Amravati", country: "India", admin: "Maharashtra", latitude: 20.937, longitude: 77.7796, timezone: IN },
  { name: "Nanded", country: "India", admin: "Maharashtra", latitude: 19.1383, longitude: 77.321, timezone: IN },
  { name: "Sangli", country: "India", admin: "Maharashtra", latitude: 16.8524, longitude: 74.5815, timezone: IN },
  { name: "Satara", country: "India", admin: "Maharashtra", latitude: 17.6915, longitude: 74.003, timezone: IN },
  { name: "Raipur", country: "India", admin: "Chhattisgarh", latitude: 21.2514, longitude: 81.6296, timezone: IN },
  { name: "Bhilai", country: "India", admin: "Chhattisgarh", latitude: 21.2094, longitude: 81.4285, timezone: IN },
  { name: "Bilaspur", country: "India", admin: "Chhattisgarh", latitude: 22.0797, longitude: 82.1409, timezone: IN },
  { name: "Gwalior", country: "India", admin: "Madhya Pradesh", latitude: 26.2183, longitude: 78.1828, timezone: IN },
  { name: "Jabalpur", country: "India", admin: "Madhya Pradesh", latitude: 23.1815, longitude: 79.9864, timezone: IN },
  { name: "Ujjain", country: "India", admin: "Madhya Pradesh", latitude: 23.1793, longitude: 75.7849, timezone: IN },
  { name: "Sagar", country: "India", admin: "Madhya Pradesh", latitude: 23.8395, longitude: 78.7394, timezone: IN },
  { name: "Rewa", country: "India", admin: "Madhya Pradesh", latitude: 24.5343, longitude: 81.3075, timezone: IN },
  { name: "Satna", country: "India", admin: "Madhya Pradesh", latitude: 24.5745, longitude: 80.8333, timezone: IN },
  { name: "Bhagalpur", country: "India", admin: "Bihar", latitude: 25.2425, longitude: 86.9842, timezone: IN },
  { name: "Muzaffarpur", country: "India", admin: "Bihar", latitude: 26.1209, longitude: 85.3647, timezone: IN },
  { name: "Gaya", country: "India", admin: "Bihar", latitude: 24.7955, longitude: 84.9994, timezone: IN },
  { name: "Purnia", country: "India", admin: "Bihar", latitude: 25.7784, longitude: 87.4744, timezone: IN },
  { name: "Darbhanga", country: "India", admin: "Bihar", latitude: 26.1524, longitude: 85.9111, timezone: IN },
  { name: "Cuttack", country: "India", admin: "Odisha", latitude: 20.4625, longitude: 85.8828, timezone: IN },
  { name: "Bhubaneswar", country: "India", admin: "Odisha", latitude: 20.2961, longitude: 85.8245, timezone: IN },
  { name: "Puri", country: "India", admin: "Odisha", latitude: 19.8135, longitude: 85.8312, timezone: IN },
  { name: "Rourkela", country: "India", admin: "Odisha", latitude: 22.2604, longitude: 84.8536, timezone: IN },
  { name: "Sambalpur", country: "India", admin: "Odisha", latitude: 21.4665, longitude: 83.9634, timezone: IN },
  { name: "Dhanbad", country: "India", admin: "Jharkhand", latitude: 23.7957, longitude: 86.4304, timezone: IN },
  { name: "Jamshedpur", country: "India", admin: "Jharkhand", latitude: 22.8046, longitude: 86.2029, timezone: IN },
  { name: "Hazaribagh", country: "India", admin: "Jharkhand", latitude: 23.9954, longitude: 85.3625, timezone: IN },
  { name: "Siliguri", country: "India", admin: "West Bengal", latitude: 26.7271, longitude: 88.3953, timezone: IN },
  { name: "Durgapur", country: "India", admin: "West Bengal", latitude: 23.5204, longitude: 87.3119, timezone: IN },
  { name: "Asansol", country: "India", admin: "West Bengal", latitude: 23.6739, longitude: 86.9524, timezone: IN },
  { name: "Howrah", country: "India", admin: "West Bengal", latitude: 22.5958, longitude: 88.2636, timezone: IN },
  { name: "Nabadwip", country: "India", admin: "West Bengal", latitude: 23.4143, longitude: 88.3719, timezone: IN },
  { name: "Srinagar", country: "India", admin: "Jammu & Kashmir", latitude: 34.0837, longitude: 74.7973, timezone: IN },
  { name: "Jammu", country: "India", admin: "Jammu & Kashmir", latitude: 32.7266, longitude: 74.857, timezone: IN },
  { name: "Leh", country: "India", admin: "Ladakh", latitude: 34.1526, longitude: 77.5771, timezone: IN },
  { name: "Panaji", country: "India", admin: "Goa", latitude: 15.4909, longitude: 73.8278, timezone: IN },
  { name: "Margao", country: "India", admin: "Goa", latitude: 15.2706, longitude: 73.9572, timezone: IN },
  { name: "Port Blair", country: "India", admin: "Andaman & Nicobar", latitude: 11.6234, longitude: 92.7265, timezone: IN },
  { name: "Imphal", country: "India", admin: "Manipur", latitude: 24.817, longitude: 93.9368, timezone: IN },
  { name: "Shillong", country: "India", admin: "Meghalaya", latitude: 25.5788, longitude: 91.8933, timezone: IN },
  { name: "Aizawl", country: "India", admin: "Mizoram", latitude: 23.7271, longitude: 92.7176, timezone: IN },
  { name: "Kohima", country: "India", admin: "Nagaland", latitude: 25.6751, longitude: 94.11, timezone: IN },
  { name: "Agartala", country: "India", admin: "Tripura", latitude: 23.8315, longitude: 91.2868, timezone: IN },
  { name: "Gangtok", country: "India", admin: "Sikkim", latitude: 27.3389, longitude: 88.6065, timezone: IN },
  { name: "Itanagar", country: "India", admin: "Arunachal Pradesh", latitude: 27.0844, longitude: 93.6053, timezone: IN },
  { name: "Dispur", country: "India", admin: "Assam", latitude: 26.1445, longitude: 91.7362, timezone: IN },
  { name: "Dibrugarh", country: "India", admin: "Assam", latitude: 27.4728, longitude: 94.912, timezone: IN },
  { name: "Silchar", country: "India", admin: "Assam", latitude: 24.8273, longitude: 92.7975, timezone: IN },
  { name: "Kathmandu", country: "Nepal", latitude: 27.7172, longitude: 85.324, timezone: "Asia/Kathmandu" },
  { name: "Pokhara", country: "Nepal", latitude: 28.2096, longitude: 83.9856, timezone: "Asia/Kathmandu" },
  { name: "Colombo", country: "Sri Lanka", latitude: 6.9271, longitude: 79.8612, timezone: "Asia/Colombo" },
  { name: "Kandy", country: "Sri Lanka", latitude: 7.2906, longitude: 80.6337, timezone: "Asia/Colombo" },
  { name: "Dhaka", country: "Bangladesh", latitude: 23.8103, longitude: 90.4125, timezone: "Asia/Dhaka" },
  { name: "Karachi", country: "Pakistan", latitude: 24.8607, longitude: 67.0011, timezone: "Asia/Karachi" },
  { name: "Lahore", country: "Pakistan", latitude: 31.5204, longitude: 74.3587, timezone: "Asia/Karachi" },
  { name: "Dubai", country: "UAE", latitude: 25.2048, longitude: 55.2708, timezone: "Asia/Dubai" },
  { name: "Abu Dhabi", country: "UAE", latitude: 24.4539, longitude: 54.3773, timezone: "Asia/Dubai" },
  { name: "Doha", country: "Qatar", latitude: 25.2854, longitude: 51.531, timezone: "Asia/Qatar" },
  { name: "Singapore", country: "Singapore", latitude: 1.3521, longitude: 103.8198, timezone: "Asia/Singapore" },
  { name: "Kuala Lumpur", country: "Malaysia", latitude: 3.139, longitude: 101.6869, timezone: "Asia/Kuala_Lumpur" },
  { name: "London", country: "United Kingdom", latitude: 51.5074, longitude: -0.1278, timezone: "Europe/London" },
  { name: "New York", country: "United States", latitude: 40.7128, longitude: -74.006, timezone: "America/New_York" },
  { name: "San Francisco", country: "United States", latitude: 37.7749, longitude: -122.4194, timezone: "America/Los_Angeles" },
  { name: "Chicago", country: "United States", latitude: 41.8781, longitude: -87.6298, timezone: "America/Chicago" },
  { name: "Toronto", country: "Canada", latitude: 43.6532, longitude: -79.3832, timezone: "America/Toronto" },
  { name: "Sydney", country: "Australia", latitude: -33.8688, longitude: 151.2093, timezone: "Australia/Sydney" },
  { name: "Melbourne", country: "Australia", latitude: -37.8136, longitude: 144.9631, timezone: "Australia/Melbourne" },
  { name: "Perth", country: "Australia", latitude: -31.9505, longitude: 115.8605, timezone: "Australia/Perth" },
  { name: "Auckland", country: "New Zealand", latitude: -36.8485, longitude: 174.7633, timezone: "Pacific/Auckland" },
  { name: "Frankfurt", country: "Germany", latitude: 50.1109, longitude: 8.6821, timezone: "Europe/Berlin" },
  { name: "Berlin", country: "Germany", latitude: 52.52, longitude: 13.405, timezone: "Europe/Berlin" },
  { name: "Munich", country: "Germany", latitude: 48.1351, longitude: 11.582, timezone: "Europe/Berlin" },
  { name: "Paris", country: "France", latitude: 48.8566, longitude: 2.3522, timezone: "Europe/Paris" },
  { name: "Amsterdam", country: "Netherlands", latitude: 52.3676, longitude: 4.9041, timezone: "Europe/Amsterdam" },
  { name: "Zurich", country: "Switzerland", latitude: 47.3769, longitude: 8.5417, timezone: "Europe/Zurich" },
  { name: "Tokyo", country: "Japan", latitude: 35.6762, longitude: 139.6503, timezone: "Asia/Tokyo" },
  { name: "Hong Kong", country: "China", latitude: 22.3193, longitude: 114.1694, timezone: "Asia/Hong_Kong" },
  { name: "Nairobi", country: "Kenya", latitude: -1.2921, longitude: 36.8219, timezone: "Africa/Nairobi" },
  { name: "Johannesburg", country: "South Africa", latitude: -26.2041, longitude: 28.0473, timezone: "Africa/Johannesburg" },
];

/** Search places by name (case-insensitive, prefix-weighted). */
export function searchPlaces(query: string, limit = 12): Place[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    // Default: a few popular cities
    return PLACES.filter((p) =>
      ["Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"].includes(p.name)
    );
  }
  const scored = PLACES.map((p) => {
    const n = p.name.toLowerCase();
    let score = -1;
    if (n === q) score = 100;
    else if (n.startsWith(q)) score = 50;
    else if (n.includes(q)) score = 10;
    else if (p.admin?.toLowerCase().includes(q)) score = 5;
    return { p, score };
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);
  return scored.map((x) => x.p);
}
