/**
 * MockAstrologyProvider — the ONLY engine wired into the app today.
 * Implements AstrologyProvider. Deterministic; every payload carries
 * ProviderInfo(mode: "mock") so the UI can label demo data honestly.
 */

import {
  HOUSE_THEMES,
  NAKSHATRAS,
  PLANETS,
  SIGNS,
  SIGN_LORDS,
  SIGN_SANSKRIT,
  nakshatraLord,
  type AstrologyInput,
  type AstrologyProvider,
  type BirthChart,
  type DayInsight,
  type HomeAstrology,
  type PlanetName,
  type PlanetPosition,
  type ProviderInfo,
  type SignName,
  type TransitEntry,
  type TransitInfo,
} from "../types";
import {
  ascendantLongitude,
  hashString,
  houseFromSign,
  isRetrograde,
  localToUTC,
  mulberry32,
  norm360,
  siderealLongitude,
  solarEvents,
  toLocalHHMM,
  hhmmToMinutes,
} from "./positions";
import { buildDasha, lordMeaning } from "./dasha";
import { buildPanchang, currentChoghadiya } from "./panchang";
import { buildCompatibility } from "./compatibility";
import { buildHoroscope } from "./horoscope";
import {
  HOUSE_THEMES_HI,
  LORD_MEANING_HI,
  nakshatraName,
  planetName,
  signName,
  type EngineLocale,
} from "../names";

export const MOCK_PROVIDER_INFO: ProviderInfo = {
  id: "mock-engine-v1",
  mode: "mock",
  label: "Demo engine",
  disclaimer:
    "Demo data — generated by a mock engine for development. Not real astronomical calculations.",
};

// ---------------------------------------------------------------- transit text

const PLANET_NATURE: Record<PlanetName, string> = {
  Sun: "confidence and visibility",
  Moon: "emotions and home life",
  Mars: "energy and drive",
  Mercury: "communication and learning",
  Jupiter: "growth and opportunity",
  Venus: "relationships and comfort",
  Saturn: "structure and responsibility",
  Rahu: "ambition and restlessness",
  Ketu: "reflection and detachment",
};

const PLANET_NATURE_HI: Record<PlanetName, string> = {
  Sun: "आत्मविश्वास और दृश्यता",
  Moon: "भावनाएँ और घरेलू जीवन",
  Mars: "ऊर्जा और जोश",
  Mercury: "संवाद और अध्ययन",
  Jupiter: "वृद्धि और अवसर",
  Venus: "रिश्ते और सुख",
  Saturn: "अनुशासन और उत्तरदायित्व",
  Rahu: "महत्वाकांक्षा और बेचैनी",
  Ketu: "चिंतन और वैराग्य",
};

function transitInterpretation(planet: PlanetName, house: number, locale: EngineLocale): string {
  if (locale === "hi") {
    const p = planetName(planet, locale);
    const theme = HOUSE_THEMES_HI[house];
    if (planet === "Saturn" || planet === "Rahu" || planet === "Ketu") {
      return `${p} इस समय आपके ${house}वें भाव से गुज़र रहा है — ${theme}। परंपरागत ज्योतिष धीमे चलने वाले ${p} को इस भाव में ${theme} से जुड़ा धैर्य माँगने वाला समय मानता है; यहाँ अर्जित फल टिकाऊ होता है।`;
    }
    return `${p} इस समय आपके ${house}वें भाव से गुज़र रहा है — ${theme}। परंपरागत ज्योतिष इस दौर में जीवन के इस क्षेत्र पर ${PLANET_NATURE_HI[planet]} का बढ़ा प्रभाव मानता है।`;
  }
  const nature = PLANET_NATURE[planet];
  const theme = HOUSE_THEMES[house].toLowerCase();
  if (planet === "Saturn" || planet === "Rahu" || planet === "Ketu") {
    return `${planet} currently moves through your ${house}th house — ${theme}. Traditional astrology reads slow-moving ${planet} here as a period that asks for patience around ${theme}; results are lasting once earned.`;
  }
  return `${planet} currently moves through your ${house}th house — ${theme}. Traditional astrology connects transiting ${planet} with heightened ${nature} in this area of life for the duration.`;
}

// ---------------------------------------------------------------- assembly

export class MockAstrologyProvider implements AstrologyProvider {
  readonly info = MOCK_PROVIDER_INFO;

  getBirthChart(input: AstrologyInput, locale: "en" | "hi" = "en"): BirthChart {
    const birthUTC = localToUTC(input.dateOfBirth, input.timeOfBirth, input.timezone);
    const seed = hashString(`${input.dateOfBirth}|${input.timeOfBirth ?? "unknown"}|${input.latitude.toFixed(4)}|${input.longitude.toFixed(4)}`);
    const rng = mulberry32(seed);

    // Ascendant
    let ascLong: number;
    if (input.timeAccuracy === "unknown" || !input.timeOfBirth) {
      // use noon reference with a deterministic spread so profiles differ
      ascLong = norm360(ascendantLongitude(birthUTC, input.latitude, input.longitude, input.timezone) + (rng() * 40 - 20));
    } else {
      ascLong = ascendantLongitude(birthUTC, input.latitude, input.longitude, input.timezone);
      if (input.timeAccuracy === "approximate") {
        ascLong = norm360(ascLong + (rng() * 10 - 5));
      }
    }
    const ascSignIndex = Math.floor(ascLong / 30);

    // Planets
    const planets: PlanetPosition[] = PLANETS.map((planet) => {
      const longitude = siderealLongitude(planet, birthUTC);
      const signIndex = Math.floor(longitude / 30);
      const nakIndex = Math.floor(longitude / (360 / 27));
      const pada = (Math.floor((longitude % (360 / 27)) / (360 / 108)) + 1) as 1 | 2 | 3 | 4;
      return {
        planet,
        longitude: Math.round(longitude * 100) / 100,
        sign: SIGNS[signIndex],
        signIndex,
        degreeInSign: Math.round((longitude % 30) * 100) / 100,
        house: houseFromSign(signIndex, ascSignIndex),
        nakshatra: NAKSHATRAS[nakIndex],
        nakshatraPada: pada,
        nakshatraLord: nakshatraLord(nakIndex),
        signLord: SIGN_LORDS[SIGNS[signIndex]],
        isRetrograde: isRetrograde(planet, birthUTC),
      };
    });

    const moon = planets.find((p) => p.planet === "Moon")!;
    const sun = planets.find((p) => p.planet === "Sun")!;

    // Houses (whole-sign)
    const houses = SIGNS.map((sign, i) => {
      const house = houseFromSign(i, ascSignIndex);
      return {
        house,
        sign,
        signIndex: i,
        signLord: SIGN_LORDS[sign],
        planets: planets.filter((p) => p.signIndex === i).map((p) => p.planet),
        theme: locale === "hi" ? HOUSE_THEMES_HI[house] : HOUSE_THEMES[house],
      };
    }).sort((a, b) => a.house - b.house);

    // Divisional charts: D1 (rashi) + D9 (navamsa)
    const navamsaSign = (longitude: number): SignName => {
      const signIndex = Math.floor(longitude / 30);
      const element = signIndex % 4; // 0 fire(?) pattern: fire,earth,air,water cycling
      const offset = element === 0 ? signIndex : element === 1 ? (signIndex + 8) % 12 : element === 2 ? (signIndex + 4) % 12 : signIndex; // movable/fixed/dual simplification
      const total = Math.floor(longitude / (10 / 3));
      return SIGNS[(offset + (total % 12)) % 12];
    };
    const d1Houses = SIGNS.map((_, i) => {
      const house = houseFromSign(i, ascSignIndex);
      return {
        house,
        sign: SIGNS[i],
        planets: planets.filter((p) => p.signIndex === i).map((p) => p.planet),
      };
    }).sort((a, b) => a.house - b.house);
    const d9AscSign = navamsaSign(ascLong);
    const d9Houses = SIGNS.map((_, i) => {
      const house = houseFromSign(i, SIGNS.indexOf(d9AscSign));
      const d9PlanetSigns = planets.map((p) => ({ planet: p.planet, sign: navamsaSign(p.longitude) }));
      return {
        house,
        sign: SIGNS[i] as SignName,
        planets: d9PlanetSigns.filter((p) => SIGNS.indexOf(p.sign) === i).map((p) => p.planet),
      };
    }).sort((a, b) => a.house - b.house);

    // Key highlights in plain language
    const ascLord = SIGN_LORDS[SIGNS[ascSignIndex]];
    const keyHighlights =
      locale === "hi"
        ? [
            {
              title: `आपकी चंद्र राशि ${signName(moon.sign, locale)} है`,
              body: `वैदिक ज्योतिष में चंद्र राशि (${signName(moon.sign, locale)}) आपका भावनात्मक आधार है — आप कैसे दिखते हैं उससे ज़्यादा, आप कैसे महसूस करते और प्रतिक्रिया देते हैं। चंद्र ${nakshatraName(moon.nakshatra, locale)} नक्षत्र में हैं, पद ${moon.nakshatraPada}।`,
            },
            {
              title: `आपका लग्न ${signName(SIGNS[ascSignIndex], locale)} है`,
              body: `लग्न आपके जन्म के क्षण पूर्वी क्षितिज पर उदित होने वाली राशि है — यह जीवन के प्रति आपके समग्र दृष्टिकोण को आकार देती है। इसके स्वामी ${planetName(ascLord, locale)} हैं, जो ${LORD_MEANING_HI[ascLord]} से जुड़े हैं।`,
            },
            {
              title: `सूर्य ${signName(sun.sign, locale)} में`,
              body: `सूर्य की राशि आपके उद्देश्य और पहचान का संकेत देती है। ${signName(sun.sign, locale)} में उद्देश्य इसी राशि के गुणों के ज़रिए व्यक्त होता है।`,
            },
            {
              title: `${nakshatraName(moon.nakshatra, locale)} नक्षत्र`,
              body: `चंद्र का नक्षत्र (जन्म-तारा) ${nakshatraName(moon.nakshatra, locale)} है, जिसके स्वामी ${planetName(moon.nakshatraLord, locale)} हैं। यही आपकी विंशोत्तरी दशा का क्रम तय करता है — जीवन के ग्रह-दौर।`,
            },
          ]
        : [
            {
              title: `Your Moon sign is ${moon.sign}`,
              body: `In Vedic astrology the Moon sign (${SIGN_SANSKRIT[moon.sign]}) is your emotional core — how you feel and respond, more than how you appear. The Moon sits in ${moon.nakshatra}, pada ${moon.nakshatraPada}.`,
            },
            {
              title: `Your ascendant is ${SIGNS[ascSignIndex]}`,
              body: `The ascendant (Lagna) is the sign rising on the eastern horizon at your birth — it shapes your overall approach to life. Its lord is ${SIGN_LORDS[SIGNS[ascSignIndex]]}, linked to ${lordMeaning(SIGN_LORDS[SIGNS[ascSignIndex]])}.`,
            },
            {
              title: `Your Sun is in ${sun.sign}`,
              body: `The Sun's sign describes your sense of purpose and identity. In ${sun.sign}, purpose is expressed through the qualities of this sign.`,
            },
            {
              title: `${moon.nakshatra} nakshatra`,
              body: `The Moon's nakshatra (birth star) is ${moon.nakshatra}, ruled by ${moon.nakshatraLord}. It sets your Vimshottari dasha sequence — the planetary phases of your life.`,
            },
          ];

    const note =
      locale === "hi"
        ? input.timeAccuracy === "unknown"
          ? "जन्म समय अज्ञात है, इसलिए लग्न और भाव अनुमानित हैं। सटीक कुंडली के लिए बाद में अपना पक्का समय जोड़ें।"
          : input.timeAccuracy === "approximate"
            ? "जन्म समय लगभग बताया गया है, इसलिए भाव-स्थितियाँ थोड़ी बदल सकती हैं।"
            : "कुंडली आपके सटीक जन्म समय से बनाई गई है।"
        : input.timeAccuracy === "unknown"
          ? "Birth time is unknown, so the ascendant and houses are estimated. Add your exact time later for an accurate chart."
          : input.timeAccuracy === "approximate"
            ? "Birth time is approximate, so house positions may shift slightly."
            : "Chart calculated from your exact birth time.";

    return {
      provider: this.info,
      input,
      ascendant: {
        sign: SIGNS[ascSignIndex],
        signIndex: ascSignIndex,
        degreeInSign: Math.round((ascLong % 30) * 100) / 100,
        lord: SIGN_LORDS[SIGNS[ascSignIndex]],
        isApproximate: input.timeAccuracy !== "exact",
      },
      moonSign: { sign: moon.sign, signIndex: moon.signIndex, sanskrit: SIGN_SANSKRIT[moon.sign] },
      sunSign: { sign: sun.sign, sanskrit: SIGN_SANSKRIT[sun.sign] },
      nakshatra: { name: moon.nakshatra, pada: moon.nakshatraPada, lord: moon.nakshatraLord },
      planets,
      houses,
      divisional:
        locale === "hi"
          ? [
              { id: "D1", name: "राशि (D1)", description: "मुख्य जन्म कुंडली — आपकी मूल रूपरेखा।", houses: d1Houses },
              {
                id: "D9",
                name: "नवांश (D9)",
                description: "'फल' कुंडली — परंपरा में विवाह, भीतरी बल और उत्तरार्ध जीवन के लिए देखी जाती है।",
                houses: d9Houses,
              },
            ]
          : [
              { id: "D1", name: "Rashi (D1)", description: "The main birth chart — your core blueprint.", houses: d1Houses },
              {
                id: "D9",
                name: "Navamsa (D9)",
                description: "The 'fruit' chart — traditionally read for marriage, inner strength and later life.",
                houses: d9Houses,
              },
            ],
      keyHighlights,
      note,
    };
  }

  getDasha(
    input: AstrologyInput,
    asOf = new Date(),
    locale: "en" | "hi" = "en"
  ): ReturnType<AstrologyProvider["getDasha"]> {
    const birthUTC = localToUTC(input.dateOfBirth, input.timeOfBirth, input.timezone);
    const moonLong = siderealLongitude("Moon", birthUTC);
    return buildDasha(moonLong, birthUTC.getTime(), asOf, this.info, locale);
  }

  getTransit(input: AstrologyInput, asOf = new Date(), locale: "en" | "hi" = "en"): TransitInfo {
    const birthUTC = localToUTC(input.dateOfBirth, input.timeOfBirth, input.timezone);
    const ascLong = ascendantLongitude(birthUTC, input.latitude, input.longitude, input.timezone);
    const ascSignIndex = Math.floor(ascLong / 30);

    const MOTION: Record<string, number> = {
      Sun: 1, Moon: 13.2, Mercury: 1.2, Venus: 1.1, Mars: 0.55, Jupiter: 0.083, Saturn: 0.033, Rahu: -0.053, Ketu: -0.053,
    };

    const transits: TransitEntry[] = PLANETS.map((planet) => {
      const longitude = siderealLongitude(planet, asOf);
      const signIndex = Math.floor(longitude / 30);
      const perDay = Math.abs(MOTION[planet]);
      const signSpanDays = 30 / perDay;
      const intoSignDays = (longitude % 30) / perDay;
      const startedOn = new Date(asOf.getTime() - intoSignDays * 86400000);
      const endsOn = new Date(startedOn.getTime() + signSpanDays * 86400000);
      const natalHouse = houseFromSign(signIndex, ascSignIndex);
      return {
        planet,
        currentSign: SIGNS[signIndex],
        currentSignIndex: signIndex,
        natalHouse,
        startedOn: startedOn.toISOString(),
        endsOn: endsOn.toISOString(),
        isRetrograde: isRetrograde(planet, asOf),
        interpretation: transitInterpretation(planet, natalHouse, locale),
      };
    });

    const slow = transits.filter((t) => ["Saturn", "Jupiter", "Rahu", "Ketu"].includes(t.planet));
    const notable = slow.map((t) =>
      locale === "hi"
        ? `${planetName(t.planet, locale)} ${signName(t.currentSign, locale)} में हैं और आपके ${t.natalHouse}वें भाव से गुज़र रहे हैं।`
        : `${t.planet} is in ${t.currentSign}, transiting your ${t.natalHouse}th house`
    );

    return { provider: this.info, asOf: asOf.toISOString(), transits, notable };
  }

  getPanchang(
    date: string,
    location: { name: string; latitude: number; longitude: number; timezone: string },
    locale: "en" | "hi" = "en"
  ) {
    return buildPanchang(date, location, this.info, locale);
  }

  getHoroscope(
    input: AstrologyInput,
    period: "daily" | "weekly" | "monthly" | "yearly",
    asOf = new Date(),
    locale: "en" | "hi" = "en"
  ) {
    const birthUTC = localToUTC(input.dateOfBirth, input.timeOfBirth, input.timezone);
    const moonLong = siderealLongitude("Moon", birthUTC);
    const moonSignIndex = Math.floor(moonLong / 30);
    return buildHoroscope(SIGNS[moonSignIndex], moonSignIndex, period, asOf, this.info, locale);
  }

  getCompatibility(
    a: { id: string; input: AstrologyInput },
    b: { id: string; input: AstrologyInput },
    locale: "en" | "hi" = "en"
  ) {
    const extract = ({ id, input }: { id: string; input: AstrologyInput }) => {
      const birthUTC = localToUTC(input.dateOfBirth, input.timeOfBirth, input.timezone);
      const moonLongitude = siderealLongitude("Moon", birthUTC);
      const marsLongitude = siderealLongitude("Mars", birthUTC);
      const ascLong = ascendantLongitude(birthUTC, input.latitude, input.longitude, input.timezone);
      return {
        id,
        name: input.name,
        moonLongitude,
        ascSignIndex: Math.floor(ascLong / 30),
        marsSignIndex: Math.floor(marsLongitude / 30),
        marsHouseFromMoon: houseFromSign(Math.floor(marsLongitude / 30), Math.floor(moonLongitude / 30)),
      };
    };
    return buildCompatibility(extract(a), extract(b), this.info, locale);
  }

  getHomeAstrology(input: AstrologyInput, asOf = new Date(), locale: "en" | "hi" = "en"): HomeAstrology {
    const chart = this.getBirthChart(input);
    const dasha = this.getDasha(input, asOf);
    const panchang = this.getPanchang(asOf.toISOString().slice(0, 10), {
      name: input.placeName,
      latitude: input.latitude,
      longitude: input.longitude,
      timezone: input.timezone,
    }, locale);

    // Day insight: seeded by (profile, date) + dasha context
    const seed = hashString(`${input.name}|${input.dateOfBirth}|${asOf.toISOString().slice(0, 10)}`);
    const rng = mulberry32(seed);
    const mahaLord = planetName(dasha.current.mahadasha.lord, locale);
    const antarLord = planetName(dasha.current.antardasha.lord, locale);
    const insights: Omit<DayInsight, "factors">[] =
      locale === "hi"
        ? [
            {
              headline: "स्थिर दिन — अपने ध्यान की रक्षा करें",
              body: `चंद्र ${panchang.nakshatra.name} में और आपकी ${antarLord} उप-दशा में होने से, परंपरागत ज्योतिष आज को कई छोटे कामों की बजाय एक स्पष्ट प्राथमिकता के लिए सबसे उपयुक्त मानता है।`,
            },
            {
              headline: "छोटी बातचीत में गहराई है",
              body: `आज चंद्र की ${panchang.nakshatra.name} स्थिति सुनने के लिए अनुकूल है। आपके अपने लोग जितने दिखते हैं, उससे ज़्यादा ग्रहणशील हैं — एक छोटी, सच्ची बातचीत बहुत दूर तक जाती है।`,
            },
            {
              headline: "गति चुपचाप बनती है",
              body: `आपकी ${mahaLord} दशा स्थिर निर्माण के लिए अनुकूल है। आज के छोटे प्रयास संचित होते हैं — भले कुछ नाटकीय न दिखे, इन पर भरोसा रखें।`,
            },
            {
              headline: "एक कोमल कद बाहर की ओर",
              body: `${antarLord} उप-दशा अवसरों को लोगों के ज़रिए लाती है। आज एक व्यक्ति तक पहुँचें — कोई गुरु, मित्र या सहकर्मी।`,
            },
          ]
        : [
            {
              headline: "A steady day — protect your focus",
              body: `With the Moon in ${panchang.nakshatra.name} and your ${dasha.current.antardasha.lord} sub-period, traditional astrology reads today as best spent on one clear priority rather than many small ones.`,
            },
            {
              headline: "Small conversations carry weight",
              body: `The Moon's placement in ${panchang.nakshatra.name} today favours listening. People close to you are more receptive than they appear — a short, honest exchange goes far.`,
            },
            {
              headline: "Momentum builds quietly",
              body: `Your ${dasha.current.mahadasha.lord} phase favours steady building. Today's small efforts compound — trust them even if nothing dramatic happens.`,
            },
            {
              headline: "Take one gentle step outward",
              body: `${dasha.current.antardasha.lord} sub-periods tend to surface opportunities through people. Reach out to one person today — a mentor, a friend, a colleague.`,
            },
          ];
    const chosen = insights[Math.floor(rng() * insights.length)];

    const nowHHMM = toLocalHHMM(asOf, input.timezone);
    const chog = currentChoghadiya(panchang, nowHHMM);

    return {
      insight: {
        ...chosen,
        factors:
          locale === "hi"
            ? [
                { label: "वर्तमान दशा", value: `${mahaLord} → ${antarLord}` },
                { label: "चंद्र नक्षत्र", value: panchang.nakshatra.name },
                { label: "तिथि", value: panchang.tithi.name },
              ]
            : [
                { label: "Current phase", value: `${dasha.current.mahadasha.lord} → ${dasha.current.antardasha.lord}` },
                { label: "Moon's nakshatra", value: panchang.nakshatra.name },
                { label: "Tithi", value: panchang.tithi.name },
              ],
      },
      today: {
        tithi: panchang.tithi.name,
        nakshatra: panchang.nakshatra.name,
        nakshatraPada: panchang.nakshatra.pada,
        rahuKaal: panchang.rahuKaal,
        choghadiyaNow: chog,
        sunrise: panchang.sunrise,
        sunset: panchang.sunset,
      },
      dasha: {
        line:
          locale === "hi"
            ? `${mahaLord} दशा · ${antarLord} उप-दशा`
            : `${dasha.current.mahadasha.lord} phase · ${dasha.current.antardasha.lord} sub-period`,
        sub:
          locale === "hi"
            ? `परंपरागत ज्योतिष इसे ${LORD_MEANING_HI[dasha.current.mahadasha.lord]} और ${LORD_MEANING_HI[dasha.current.antardasha.lord]} से जोड़ता है।`
            : `Traditional astrology links this with ${lordMeaning(dasha.current.mahadasha.lord)} and ${lordMeaning(dasha.current.antardasha.lord)}.`,
      },
      transit: {
        line: chart
          ? (() => {
              const jup = this.getTransit(input, asOf).transits.find((t) => t.planet === "Jupiter");
              if (!jup) return "";
              return locale === "hi"
                ? `गुरु आपके ${jup.natalHouse}वें भाव से गुज़र रहे हैं — ${HOUSE_THEMES_HI[jup.natalHouse]}।`
                : `Jupiter transits your ${jup.natalHouse}th house — ${HOUSE_THEMES[jup.natalHouse].toLowerCase()}.`;
            })()
          : "",
      },
    };
  }

  /** Helper used by the pre-consultation consent screen. */
  solarEventsFor(dateStr: string, input: AstrologyInput) {
    return solarEvents(dateStr, input.latitude, input.longitude, input.timezone);
  }
}

// singleton
let instance: MockAstrologyProvider | null = null;
export function getMockAstrologyProvider(): MockAstrologyProvider {
  if (!instance) instance = new MockAstrologyProvider();
  return instance;
}

export { hhmmToMinutes };
