"use client";

/**
 * Client-side report document builder. Produces a clean, self-contained HTML
 * document (print CSS included) used for both the download file and the
 * print/preview view. Honest by design: demo badge + guidance-not-guarantee
 * footer travel with the file.
 */

export interface ReportDocumentInput {
  title: string;
  type: string;
  sections: { heading: string; body: string }[];
  profileName?: string | null;
  createdAt: string;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatLongDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "—";
  return d.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
}

export function buildReportHtml(report: ReportDocumentInput): string {
  const sectionsHtml = report.sections
    .map((s) => {
      const paragraphs = s.body
        .split(/\n\n+/)
        .map((p) => `<p>${esc(p).replace(/\n/g, "<br />")}</p>`)
        .join("\n");
      return `<section>\n<h2>${esc(s.heading)}</h2>\n${paragraphs}\n</section>`;
    })
    .join("\n");

  const metaParts = [
    `Created ${formatLongDate(report.createdAt)}`,
    report.profileName ? `For ${esc(report.profileName)}` : null,
  ]
    .filter(Boolean)
    .join(" · ");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(report.title)} — Tara</title>
<style>
  :root { color-scheme: light; }
  body {
    font-family: Georgia, "Times New Roman", serif;
    color: #241f1a;
    background: #ffffff;
    max-width: 720px;
    margin: 0 auto;
    padding: 48px 28px 56px;
    line-height: 1.7;
  }
  header { border-bottom: 2px solid #a2563b; padding-bottom: 18px; margin-bottom: 28px; }
  h1 { font-size: 28px; line-height: 1.2; margin: 0; color: #241f1a; }
  .meta { color: #6d6355; font-size: 13px; margin-top: 6px; }
  .badge {
    display: inline-block; border: 1px solid #d8cec0; border-radius: 999px;
    padding: 1px 10px; font-size: 11px; color: #6d6355; margin-left: 6px;
    font-family: -apple-system, "Segoe UI", sans-serif;
  }
  h2 { font-size: 18px; color: #8a4629; margin: 34px 0 10px; }
  p { margin: 0 0 12px; font-size: 14.5px; }
  section { break-inside: auto; }
  footer {
    margin-top: 44px; padding-top: 14px; border-top: 1px solid #e6ddd0;
    color: #8a8172; font-size: 12px;
    font-family: -apple-system, "Segoe UI", sans-serif;
  }
  @media print {
    body { max-width: none; margin: 0; padding: 0; }
    @page { margin: 16mm; }
    h2 { break-after: avoid; }
  }
</style>
</head>
<body>
<header>
  <h1>${esc(report.title)}</h1>
  <div class="meta">${metaParts}<span class="badge">Demo data</span></div>
</header>
${sectionsHtml}
<footer>Generated by Tara — reflective guidance, never a guarantee. This is a demo build; chart positions come from the demo engine while a verified engine is being connected.</footer>
</body>
</html>`;
}

/** Download the report as a standalone HTML file. */
export function downloadReportHtml(report: ReportDocumentInput): void {
  const html = buildReportHtml(report);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `tara-${report.type}-report.html`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

/** Print via a hidden iframe carrying the same clean document. */
export function printReportHtml(report: ReportDocumentInput): void {
  const html = buildReportHtml(report);
  const iframe = document.createElement("iframe");
  iframe.setAttribute("aria-hidden", "true");
  iframe.title = "print";
  iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0;visibility:hidden;";
  iframe.srcdoc = html;
  iframe.onload = () => {
    const win = iframe.contentWindow;
    if (!win) {
      iframe.remove();
      return;
    }
    const cleanup = () => iframe.remove();
    win.addEventListener("afterprint", cleanup, { once: true });
    setTimeout(cleanup, 90_000); // safety net
    win.focus();
    win.print();
  };
  document.body.appendChild(iframe);
}
